version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: npm install
      - run: ls -l
      - run: ls -l src/js/Helpers
      - run: npm run build
      - run: npm run deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy:
          filters:
                branches:
                  only:
                    - master