version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm build
      - run: npm deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy:
          filters:
                branches:
                  only:
                    - master