version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run: npm run deploy
  git-test:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: node ./getGit.js
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy:
          filters:
                branches:
                  only:
                    - master
  git_test:
    jobs:
      - git-test:
          filters:
                branches:
                  only:
                    - git-test