version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo hello-build
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo hello-test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test